-- Active: 1689142396029@@127.0.0.1@3306@tweets
-- -- insert into employee(first_name,last_name,age,current_status) VALUES('abhi','anand',21,'hi this is abhi');

--   using primary key and auto increment 
-- create table employees(
--     id int AUTO_INCREMENT,
--     last_name text not NULL,
--     first_name text not NULL,
--     middle_name text,
--     age int,
--     current_status VARCHAR(100) not NULL DEFAULT 'employed',
--     PRIMARY KEY(id)
-- );

-- Multiple inserting in the table

-- CREATE TABLE cats (
--     cat_id INT AUTO_INCREMENT,
--     name VARCHAR(100),
--     breed VARCHAR(100),
--     age INT,
--     PRIMARY KEY (cat_id)
-- ); 
-- INSERT INTO cats(name, breed, age) 
-- VALUES ('Ringo', 'Tabby', 4),
--        ('Cindy', 'Maine Coon', 10),
--        ('Dumbledore', 'Maine Coon', 11),
--        ('Egg', 'Persian', 4),
--        ('Misty', 'Tabby', 13),
--        ('George Michael', 'Ragdoll', 9),
--        ('Jackson', 'Sphynx', 7);